# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-19 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='picure',
            new_name='picture',
        ),
    ]
